### ISSUE TITLE
Config.yml config error

### ISSUE THREAD

**Issue by brandonskerritt** [Ciphey/Ciphey#180]
Place this config file `config.yml` into appdirs:
```yaml
params:
  regex:
    regex:
    - FLAG{*.}
    - CTF{*.}
    - HTB{.*}
    - {
    - THM{.*}
```

Run Ciphey. It will error with:
[message(3).txt](https://github.com/Ciphey/Ciphey/files/4937931/message.3.txt)
